name: zfs_backup_helper
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  riverpod: ^1.0.3
  rxdart: ^0.27.4

dev_dependencies:
  build_runner: ^2.1.11
  dart_pre_commit: ^3.0.1
  dart_test_tools: ^3.3.2
  freezed: ^2.0.4
  json_serializable: ^6.3.1
  test: ^1.21.4
